package tests;
import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.By;
import utilities.TestBase;
public class Day07_Alerts extends TestBase {
    @Test
    public void acceptAlert() throws InterruptedException {
//        acceptAlert() => click on the first alert,
        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");
        driver.findElement(By.xpath("//button[@onclick='jsAlert()']")).click();
        Thread.sleep(2000);//just using hard wait to execute to slower to see the steps
//         verify the text “I am a JS Alert” ,
        String actualAlertText = driver.switchTo().alert().getText();
        Assert.assertEquals("I am a JS Alert",actualAlertText);
//        click OK ,
        driver.switchTo().alert().accept();
        Thread.sleep(2000);
//        and Verify “You successfully clicked an alert”
        String actualResult = driver.findElement(By.id("result")).getText();
        Assert.assertEquals("You successfully clicked an alert",actualResult);
        Thread.sleep(2000);
    }
    @Test
    public void dismissAlert() throws InterruptedException {
//        dismissAlert()=> click on the second alert,
        Thread.sleep(3000);//just using hard wait to execute to slower to see the steps
        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");
        driver.findElement(By.xpath("//button[@onclick='jsConfirm()']")).click();
//         verify text "I am a JS Confirm”,
        Thread.sleep(3000);
        String actualAlertText = driver.switchTo().alert().getText();
        Assert.assertEquals("I am a JS Confirm",actualAlertText);
//        click cancel,
        driver.switchTo().alert().dismiss();
        Thread.sleep(3000);
//        and Verify “You clicked: Cancel”
        String actualResult = driver.findElement(By.id("result")).getText();
        Assert.assertEquals("You clicked: Cancel",actualResult);
        Thread.sleep(3000);
    }
    @Test
    public void sendKeysAlert() throws InterruptedException {
        Thread.sleep(3000);
//        sendKeysAlert()=> click on the third alert,
        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");
        driver.findElement(By.xpath("//button[@onclick='jsPrompt()']")).click();
        Thread.sleep(3000);//just using hard wait to execute to slower to see the steps
//        verify text “I am a JS prompt”,
        String actualAlertText = driver.switchTo().alert().getText();
        Assert.assertEquals("I am a JS prompt",actualAlertText);
//        type “Hello World”,
        driver.switchTo().alert().sendKeys("Hello World");
//        click OK,
        driver.switchTo().alert().accept();
        Thread.sleep(3000);
//        and Verify “You entered: Hello World”
        String actualResult = driver.findElement(By.id("result")).getText();
        Assert.assertEquals("You entered: Hello World",actualResult);
        Thread.sleep(3000);
    }
    /*
    What is an alert?
        Alerts are a pop up that is generated by javascript.
        When there is an alerts, we must handle the alerts.
        Otherwise, we cannot continue to the test execution

    How do you handle alert?
       First we cannot inspect js alerts. We should first switch
      to the alert and use accept() to click ok, dismiss() to
     click cancel, sendKeys() to type, getText() to get the
      text from the alert
     */
}
/*
TestBase
Utility class
There is before and after methods in this class
Our test base is abstract so we just extend and use the methods
This kind of utility classes makes the actual test classes short and clean
Iframes
Iframe is used to add page within a page, maps, videos, scrollbars,…
Driver must switch to iframe first to see the elements in the frame
driver.switchTo().frame(“by using id/name, index, or web-element”);-> get in
driver.switchTo().parentFrame() or defaultContent()
Multiple windows
The multiple windows may open when there is a link that opens in a new TAB or WINDOWS
We use windowHandle to get the current window id, windowHandles to get all open windows ids
We use set of list to get all window ids and switch to the desired window using loop and if condition
Alerts
Alerts are generated by javascript alerts. For example when clicking a button, we can see informative alerts
When there is an alert, we must handle it first to continue the test execution.
We cannot inspect alerts, but we can handle alerts by switching them first
driver.switchTo().alert().  —-accept(), dissmiss(), getText(), and sendKeys()——
 */